name: Deploy to EC2

on:
    workflow_run:
        workflows: ["Push docker images"]
        types:
            - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script: |
            sudo su
            sudo apt-get update
            yes | sudo apt-get install docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo usermod -aG docker ubuntu
            exec bash
      - name: Install docker-compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script: |
            sudo su
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_PEM }}
          script: |
            sudo su
            git clone https://github.com/carolahn/tcc-dockerized-full-stack.git
            cd tcc-dockerized-full-stack
            export COMPOSE_FILE=docker-compose.prod.yml
            sudo docker-compose up --build -d
          